### ISSUE TITLE
PhysicalNetlistToDcp doesn't appear to respect site pip selection in some cases

### ISSUE THREAD

**Issue by litghost** [Xilinx/RapidWright#142]
As part of bring up of the FPGA interchange on nextpnr, the initial site router is avoiding use of local inverters.  It was expected that the FPGA interchange physical netlist would be able to specify site routing that is sub-optimal with respect to constant networks and local inverters to allow an easier initial implementation.  However that doesn't appear to be the case.

In the attached file, [ram_test.tar.gz](https://github.com/Xilinx/RapidWright/files/6192085/ram_test.tar.gz), there is an example of a physical netlist (and DCP) where the non-inverting path is taken for `GLOBAL_LOGIC0`, see snippet from YAML:
```
        branches:
          - routeSegment:
              pip:
                tile: INT_L_X6Y45
                wire0: GFAN0
                wire1: CTRL_L1
                forward: true
                isFixed: false
            branches:
              - routeSegment:
                  pip:
                    tile: BRAM_L_X6Y45
                    wire0: BRAM_CTRL1_0
                    wire1: BRAM_RAMB18_RSTREGB
                    forward: true
                    isFixed: false
                branches:
                  - routeSegment:
                      sitePin:
                        site: RAMB18_X0Y19
                        pin: RSTREGB
                    branches:
                      - routeSegment:
                          belPin:
                            site: RAMB18_X0Y19
                            bel: RSTREGB
                            pin: RSTREGB
                        branches:
                          - routeSegment:
                              sitePIP:
                                site: RAMB18_X0Y19
                                bel: RSTREGBINV
                                pin: RSTREGB
                                isFixed: false
                                isInverting: false
                            branches:
                              - routeSegment:
                                  belPin:
                                    site: RAMB18_X0Y19
                                    bel: RAMB18E1
                                    pin: RSTREGB
                                branches: []
```

However the DCP generated uses the inverting path (e.g. BEL pin `RSTREGB_B`) for the site routing mux `RAMB18_X0Y19/RSTREGBINV`.  The key here is BEL pin `RSTREGB_B` vs `RSTREGB`.  The documentation for `addSitePIP` indicates that the equivalent command in Vivado would be:
```
set_property MANUAL_ROUTING [get_property SITE_TYPE $site] $site;set_property SITE_PIPS "[get_property SITE_PIPS $site] $sitePIP" $site;set_property MANUAL_ROUTING {} $site
```

That property does not appear to be site in the DCP generated from the physical netlist attached.  I've tried swapping the order of site pip (which uses `addSitePip`) versus BEL pin (which uses `routeIntraSiteNet`). I've also tried using `routeIntraSiteNet` to route the relevant net directly to the input site PIP BEL pin.  None of this appear to cause the DCP to respsect the original intent.

Is this a limitation in RapidWright?  A straight forward bug in the `PhysNetlistReader`?
